// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCONcF_GwFoeCtLCUPjJn9skY4-sviWJlQ',
    appId: '1:495315994208:web:aa3a0802f3e2fdbda96505',
    messagingSenderId: '495315994208',
    projectId: 'essentials-47d9a',
    authDomain: 'essentials-47d9a.firebaseapp.com',
    databaseURL: 'https://essentials-47d9a-default-rtdb.firebaseio.com',
    storageBucket: 'essentials-47d9a.firebasestorage.app',
    measurementId: 'G-8REVW8XYE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsZTaIRkcwLZcP_TQKh6FuKD2zmxlZKzo',
    appId: '1:495315994208:android:9d6409dd3af12a7ca96505',
    messagingSenderId: '495315994208',
    projectId: 'essentials-47d9a',
    databaseURL: 'https://essentials-47d9a-default-rtdb.firebaseio.com',
    storageBucket: 'essentials-47d9a.firebasestorage.app',
  );
}
